require("which-key").register({
    ['c'] = {':Neogit', 'Git commit menu'},
    ['g'] = {':DiffviewOpen<CR>', 'Git changes'},
    ['l'] = {':DiffviewLog<CR>', 'Git log'},
    ['f'] = {':DiffviewFileHistory<CR>', 'Open git file history'},
    [']'] = {"&diff ? ']c' : ':Gitsigns next_hunk<CR>'", 'Move to next hunk'},
    ['['] = {"&diff ? ']c' : ':Gitsigns prev_hunk<CR>'", 'Move to next hunk'},
    ['sb'] = {':Gitsigns stage_buffer<CR>', 'Stage current buffer'},
    ['sh'] = {':Gitsigns stage_hunk<CR>', 'Stage current hunk'},
    ['su'] = {'::Gitsigns undo_stage_hunk<CR>', 'Undo stage hunk'},
    ['sl'] = {':lua require"gitsigns".stage_hunk({vim.fn.line("."), vim.fn.line("v")})<CR>', 'Stage line hunk'},
    ['rb'] = {':Gitsigns reset_buffer<CR>', 'Reset buffer signs'},
    ['rh'] = {':Gitsigns reset_hunk<CR>', 'Reset current hunk'},
    ['ri'] = {':Gitsigns reset_buffer_index<CR>', 'Reset buffer index'},
    ['rl'] = {':lua require"gitsigns".reset_hunk({vim.fn.line("."), vim.fn.line("v")})<CR>', 'Reset line hunk'},
    ['p'] = {':Gitsigns preview_hunk<CR>', 'Preview current hunk'},
    ['<tab>'] = {':Gitsigns blame_line<CR>', 'Blame current line'},
    ['d'] = {':Gitsigns diffthis<CR>', 'Show line different'},
    ['/b'] = {':Gitsigns toggle_current_line_blame<CR>', 'Toggle line blame hints'},
    ['B'] = {':Git blame<CR>', 'Show git blame'},
    ['D'] = {':Git difftool<CR>', 'Show file git differences'},
    ['S'] = {':Git show<CR>', 'Show commit changes'},
    ['M'] = {':Git mergetool<CR>', 'Show git merge tool'},
    ['tt'] = {':Tig<CR>', 'Toggle git project tool menu'},
    ['tb'] = {':TigBlame<CR>', 'Toggle git project blame tool menu'},
    ['tg'] = {':TigGrep<CR>', 'Toggle git project grep tool menu'},
    ['ts'] = {':TigStatus<CR>', 'Toggle git project status tool menu'},
}, {
    prefix = '<C-g>',
    silent = true,
    noremap = true,
    nowait = false,
})
